### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/sweet-shop-reaction-game#5]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by lauraclay** [comment]
Images need to be moved into the images folder and links updated.

**Comment by MissPhilbin** [comment]
I've moved the images, thanks!

**Comment by bennuttall** [comment]
No component images required, have moved non-hardware stuff to `extras.md`

**Comment by bennuttall** [comment]
This needs a GPIO pinout diagram from Sam at some point to replace [this image](https://github.com/raspberrypilearning/reaction-game/blob/master/images/gpio.png)

Might need to wait for new Scratch GPIO?

**Comment by LornaLynch** [comment]
We still need a new pinout diagram to replace the image in section 4, as above.

**Comment by LornaLynch** [comment]
@bennuttall @MissPhilbin FYI we still need the new pinout diagram to replace the image in section 4 of the worksheet. After that, it's all done.

**Comment by bennuttall** [comment]
It's ready, just waiting for new Scratch to be made available.

**Comment by LornaLynch** [comment]
Jolly good: I didn't realise :)
