### ISSUE TITLE
Copy Edit Branch: Update

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/sweet-shop-reaction-game#7]
@lauraclay @LornaLynch I've updated this resource on the following branch called [update](https://github.com/raspberrypilearning/sweet-shop-reaction-game/tree/update) 

Would you mind giving it a once over before we merge it? Many thanks.

**Comment by LornaLynch** [comment]
On it now :)

**Comment by LornaLynch** [comment]
We've checked it through now @MissPhilbin :)
